# Generated by Django 5.2.1 on 2026-07-18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("dotykacka", "0014_promote_dotykacka_refresh_tokens"),
        ("integrations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CommunicationDelivery",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("channel", models.CharField(choices=[("email", "Email")], default="email", max_length=16)),
                ("template_key", models.CharField(default="loyalty-card-ready-v1", max_length=80)),
                ("generation", models.PositiveIntegerField(default=1)),
                ("recipient_sha256", models.CharField(max_length=64)),
                ("subject_snapshot", models.CharField(max_length=240)),
                ("status", models.CharField(choices=[("sending", "Sending"), ("sent", "Sent"), ("outcome_unknown", "Outcome unknown")], db_index=True, default="sending", max_length=24)),
                ("started_at", models.DateTimeField()),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("customer", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="communication_deliveries", to="dotykacka.klient")),
                ("integration_job", models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name="communication_delivery", to="integrations.integrationjob")),
                ("tenant", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="communication_deliveries", to="dotykacka.tenant")),
            ],
            options={"ordering": ("-created_at", "-pk")},
        ),
    ]
