# Generated by Django 5.2.16 on 2026-07-19 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communicationdelivery',
            name='channel',
            field=models.CharField(choices=[('email', 'E-mail')], default='email', max_length=16),
        ),
        migrations.AlterField(
            model_name='communicationdelivery',
            name='status',
            field=models.CharField(choices=[('sending', 'Wysyłanie'), ('sent', 'Wysłano'), ('outcome_unknown', 'Wynik nieznany')], db_index=True, default='sending', max_length=24),
        ),
    ]
