# Generated by Django 5.2.17 on 2026-10-08 17:01

import communications.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0002_alter_communicationdelivery_channel_and_more'),
        ('dotykacka', '0016_alter_integrationconnection_provider'),
        ('integrations', '0002_alter_integrationjob_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('goal', models.TextField()),
                ('reference_links', models.JSONField(blank=True, default=list)),
                ('subject', models.CharField(blank=True, max_length=240)),
                ('preheader', models.CharField(blank=True, max_length=240)),
                ('html_content', models.TextField(blank=True)),
                ('text_content', models.TextField(blank=True)),
                ('content_snapshot', models.JSONField(blank=True, default=dict)),
                ('generation_source', models.CharField(choices=[('local', 'Generator lokalny'), ('openai', 'OpenAI')], default='local', max_length=16)),
                ('ai_model', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(choices=[('draft', 'Szkic'), ('scheduled', 'Zaplanowana'), ('sending', 'Wysyłanie'), ('sent', 'Wysłana'), ('partially_sent', 'Wysłana częściowo'), ('cancelled', 'Anulowana')], db_index=True, default='draft', max_length=24)),
                ('scheduled_for', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('recipient_count', models.PositiveIntegerField(default=0)),
                ('sent_count', models.PositiveIntegerField(default=0)),
                ('failed_count', models.PositiveIntegerField(default=0)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_email_campaigns', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='email_campaigns', to='dotykacka.tenant')),
            ],
            options={
                'ordering': ('-created_at', '-pk'),
            },
        ),
        migrations.CreateModel(
            name='CampaignRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_snapshot', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('pending', 'Oczekuje'), ('sending', 'Wysyłanie'), ('sent', 'Wysłano'), ('failed', 'Błąd')], db_index=True, default='pending', max_length=16)),
                ('error_code', models.CharField(blank=True, max_length=80)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='campaign_recipients', to='dotykacka.klient')),
                ('integration_job', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='campaign_recipient', to='integrations.integrationjob')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='campaign_recipients', to='dotykacka.tenant')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recipients', to='communications.emailcampaign')),
            ],
            options={
                'ordering': ('created_at', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='CampaignAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(max_length=500, upload_to=communications.models.campaign_asset_path)),
                ('original_name', models.CharField(max_length=240)),
                ('content_type', models.CharField(blank=True, max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_campaign_assets', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='campaign_assets', to='dotykacka.tenant')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='communications.emailcampaign')),
            ],
            options={
                'ordering': ('created_at', 'pk'),
            },
        ),
        migrations.AddIndex(
            model_name='emailcampaign',
            index=models.Index(fields=['tenant', 'status', 'scheduled_for'], name='campaign_tenant_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='campaignrecipient',
            constraint=models.UniqueConstraint(fields=('campaign', 'customer'), name='unique_campaign_customer_recipient'),
        ),
    ]
