ServerName localhost

WSGIScriptAlias / /var/www/loyalty_platform/loyalty_platform/wsgi.py
WSGIPythonPath /var/www/loyalty_platform
WSGIDaemonProcess django processes=1 threads=3 \
    python-home=/opt/venv \
    python-path=/var/www/loyalty_platform
WSGIProcessGroup django

<VirtualHost *:80>
    UseCanonicalName Off
    ServerAdmin webmaster@localhost
    DocumentRoot /var/www/loyalty_platform/staticfiles

    Alias /media/ /var/www/loyalty_platform/media/
    <Directory /var/www/loyalty_platform/media/>
        Require all granted
        Options FollowSymLinks
    </Directory>

    Alias /static/ /var/www/loyalty_platform/staticfiles/
    <Directory /var/www/loyalty_platform/staticfiles/>
        Require all granted
        Options FollowSymLinks
    </Directory>

    <Directory /var/www/loyalty_platform/loyalty_platform/>
        <Files wsgi.py>
            Require all granted
        </Files>
    </Directory>

    ErrorLog /proc/self/fd/2
    CustomLog /proc/self/fd/1 combined
</VirtualHost>
