ServerName localhost

WSGIScriptAlias / /var/www/turnkey_project/turnkey_project/wsgi.py
WSGIPythonPath /var/www/turnkey_project
WSGIDaemonProcess django processes=1 threads=3 \
    python-home=/opt/venv \
    python-path=/var/www/turnkey_project
WSGIProcessGroup django

<VirtualHost *:80>
    UseCanonicalName Off
    ServerAdmin webmaster@localhost
    DocumentRoot /var/www/turnkey_project/staticfiles

    Alias /media/ /var/www/turnkey_project/media/
    <Directory /var/www/turnkey_project/media/>
        Require all granted
        Options FollowSymLinks
    </Directory>

    Alias /static/ /var/www/turnkey_project/staticfiles/
    <Directory /var/www/turnkey_project/staticfiles/>
        Require all granted
        Options FollowSymLinks
    </Directory>

    <Directory /var/www/turnkey_project/turnkey_project/>
        <Files wsgi.py>
            Require all granted
        </Files>
    </Directory>

    ErrorLog /proc/self/fd/2
    CustomLog /proc/self/fd/1 combined
</VirtualHost>
