# Generated by Django 5.2.1 on 2026-07-17 20:52

import billing.models
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dotykacka', '0013_backfill_card_designs'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-starts_at',),
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=60, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('public_description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='PriceBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=60, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='PlanVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('billing_interval', models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly')], default='monthly', max_length=16)),
                ('recurring_amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('currency', models.CharField(default='PLN', max_length=3, validators=[django.core.validators.RegexValidator(message='Use a three-letter ISO 4217 currency code, for example PLN.', regex='^[A-Z]{3}$')])),
                ('tax_display', models.CharField(choices=[('inclusive', 'Tax included'), ('exclusive', 'Tax added'), ('not_applicable', 'Tax not applicable')], default='inclusive', max_length=20)),
                ('tax_rate', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='Decimal rate, for example 0.2300 for 23%.', max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.0000'))])),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_plan_versions', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='billing.plan')),
            ],
            options={
                'ordering': ('plan__name', '-version'),
            },
        ),
        migrations.CreateModel(
            name='EntitlementPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_seat_limit', models.PositiveIntegerField(blank=True, null=True)),
                ('card_issuance_limit', models.PositiveIntegerField(blank=True, null=True)),
                ('included_print_quantity', models.PositiveIntegerField(default=0)),
                ('unused_allowance_rolls_over', models.BooleanField(default=False)),
                ('print_overage_allowed', models.BooleanField(default=True)),
                ('plan_version', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='entitlement_policy', to='billing.planversion')),
            ],
        ),
        migrations.CreateModel(
            name='PriceBookVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('currency', models.CharField(default='PLN', max_length=3, validators=[django.core.validators.RegexValidator(message='Use a three-letter ISO 4217 currency code, for example PLN.', regex='^[A-Z]{3}$')])),
                ('tax_display', models.CharField(choices=[('inclusive', 'Tax included'), ('exclusive', 'Tax added'), ('not_applicable', 'Tax not applicable')], default='inclusive', max_length=20)),
                ('tax_rate', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.0000'))])),
                ('shipping_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_price_book_versions', to=settings.AUTH_USER_MODEL)),
                ('price_book', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='billing.pricebook')),
            ],
            options={
                'ordering': ('price_book__name', '-version'),
            },
        ),
        migrations.CreateModel(
            name='CardPriceTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minimum_quantity', models.PositiveIntegerField(default=1)),
                ('maximum_quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('unit_amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('price_book_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='card_price_tiers', to='billing.pricebookversion')),
            ],
            options={
                'ordering': ('minimum_quantity',),
            },
        ),
        migrations.CreateModel(
            name='CardPack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('purchased_quantity', models.PositiveIntegerField()),
                ('consumed_quantity', models.PositiveIntegerField(default=0)),
                ('purchase_amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('currency', models.CharField(max_length=3, validators=[django.core.validators.RegexValidator(message='Use a three-letter ISO 4217 currency code, for example PLN.', regex='^[A-Z]{3}$')])),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='card_packs', to='dotykacka.tenant')),
                ('price_book_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='card_packs', to='billing.pricebookversion')),
            ],
            options={
                'ordering': ('expires_at', 'created_at', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('accepted', 'Accepted'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='draft', max_length=16)),
                ('idempotency_key', models.CharField(max_length=180)),
                ('quantity', models.PositiveIntegerField()),
                ('included_quantity', models.PositiveIntegerField(default=0)),
                ('pack_quantity', models.PositiveIntegerField(default=0)),
                ('billable_quantity', models.PositiveIntegerField(default=0)),
                ('currency', models.CharField(max_length=3, validators=[django.core.validators.RegexValidator(message='Use a three-letter ISO 4217 currency code, for example PLN.', regex='^[A-Z]{3}$')])),
                ('subtotal_amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('shipping_amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('tax_amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('snapshot', models.JSONField(default=dict)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('billing_period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quotes', to='billing.billingperiod')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_billing_quotes', to=settings.AUTH_USER_MODEL)),
                ('price_book_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quotes', to='billing.pricebookversion')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='billing_quotes', to='dotykacka.tenant')),
            ],
            options={
                'ordering': ('-created_at', '-pk'),
            },
        ),
        migrations.CreateModel(
            name='CardPackAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('card_pack', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quote_allocations', to='billing.cardpack')),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pack_allocations', to='billing.quote')),
            ],
            bases=(billing.models.AppendOnlyMixin, models.Model),
        ),
        migrations.CreateModel(
            name='QuoteLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField()),
                ('kind', models.CharField(choices=[('included', 'Included allowance'), ('pack', 'Card pack'), ('production', 'Card production'), ('shipping', 'Shipping'), ('tax', 'Tax')], max_length=16)),
                ('description', models.CharField(max_length=240)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='billing.quote')),
            ],
            options={
                'ordering': ('position',),
            },
            bases=(billing.models.AppendOnlyMixin, models.Model),
        ),
        migrations.CreateModel(
            name='TenantSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('paused', 'Paused'), ('cancelled', 'Cancelled')], default='draft', max_length=16)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='billing.planversion')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='dotykacka.tenant')),
            ],
            options={
                'ordering': ('-starts_at', '-pk'),
            },
        ),
        migrations.AddField(
            model_name='quote',
            name='subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quotes', to='billing.tenantsubscription'),
        ),
        migrations.AddField(
            model_name='billingperiod',
            name='subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='billing_periods', to='billing.tenantsubscription'),
        ),
        migrations.CreateModel(
            name='UsageEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('physical_card_issued', 'Physical card issued'), ('virtual_card_issued', 'Virtual card issued'), ('physical_card_produced', 'Physical card produced')], max_length=32)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('idempotency_key', models.CharField(max_length=180)),
                ('reference_type', models.CharField(blank=True, max_length=80)),
                ('reference_id', models.CharField(blank=True, max_length=120)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('occurred_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('billing_period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usage_events', to='billing.billingperiod')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usage_events', to='billing.tenantsubscription')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='billing_usage_events', to='dotykacka.tenant')),
            ],
            options={
                'ordering': ('-occurred_at', '-pk'),
            },
            bases=(billing.models.AppendOnlyMixin, models.Model),
        ),
        migrations.AddConstraint(
            model_name='planversion',
            constraint=models.UniqueConstraint(fields=('plan', 'version'), name='billing_unique_plan_version'),
        ),
        migrations.AddConstraint(
            model_name='pricebookversion',
            constraint=models.UniqueConstraint(fields=('price_book', 'version'), name='billing_unique_price_book_version'),
        ),
        migrations.AddConstraint(
            model_name='cardpricetier',
            constraint=models.UniqueConstraint(fields=('price_book_version', 'minimum_quantity'), name='billing_unique_price_tier_start'),
        ),
        migrations.AddConstraint(
            model_name='cardpricetier',
            constraint=models.CheckConstraint(condition=models.Q(('minimum_quantity__gt', 0)), name='billing_price_tier_min_positive'),
        ),
        migrations.AddConstraint(
            model_name='cardpricetier',
            constraint=models.CheckConstraint(condition=models.Q(('maximum_quantity__isnull', True), ('maximum_quantity__gte', models.F('minimum_quantity')), _connector='OR'), name='billing_price_tier_valid_range'),
        ),
        migrations.AddConstraint(
            model_name='cardpack',
            constraint=models.CheckConstraint(condition=models.Q(('purchased_quantity__gt', 0)), name='billing_card_pack_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='cardpack',
            constraint=models.CheckConstraint(condition=models.Q(('consumed_quantity__lte', models.F('purchased_quantity'))), name='billing_card_pack_not_overconsumed'),
        ),
        migrations.AddConstraint(
            model_name='cardpackallocation',
            constraint=models.UniqueConstraint(fields=('quote', 'card_pack'), name='billing_unique_quote_pack_allocation'),
        ),
        migrations.AddConstraint(
            model_name='cardpackallocation',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='billing_pack_allocation_positive'),
        ),
        migrations.AddConstraint(
            model_name='quoteline',
            constraint=models.UniqueConstraint(fields=('quote', 'position'), name='billing_unique_quote_line_position'),
        ),
        migrations.AddConstraint(
            model_name='quote',
            constraint=models.UniqueConstraint(fields=('tenant', 'idempotency_key'), name='billing_unique_tenant_quote_key'),
        ),
        migrations.AddConstraint(
            model_name='quote',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='billing_quote_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='billingperiod',
            constraint=models.UniqueConstraint(fields=('subscription', 'starts_at', 'ends_at'), name='billing_unique_subscription_period'),
        ),
        migrations.AddConstraint(
            model_name='billingperiod',
            constraint=models.CheckConstraint(condition=models.Q(('ends_at__gt', models.F('starts_at'))), name='billing_period_end_after_start'),
        ),
        migrations.AddConstraint(
            model_name='usageevent',
            constraint=models.UniqueConstraint(fields=('tenant', 'idempotency_key'), name='billing_unique_tenant_usage_key'),
        ),
        migrations.AddConstraint(
            model_name='usageevent',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='billing_usage_quantity_positive'),
        ),
    ]
