# Generated by Django 5.2.1 on 2026-07-17 23:27

import billing.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrintQuoteConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('included_quantity', models.PositiveIntegerField(default=0)),
                ('pack_quantity', models.PositiveIntegerField(default=0)),
                ('billable_quantity', models.PositiveIntegerField(default=0)),
                ('reference_type', models.CharField(max_length=80)),
                ('reference_id', models.CharField(max_length=120)),
                ('consumed_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('quote', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='print_consumption', to='billing.quote')),
                ('usage_event', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='print_quote_consumption', to='billing.usageevent')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('included_quantity__gte', 0)), name='billing_consumption_included_nonnegative'), models.CheckConstraint(condition=models.Q(('pack_quantity__gte', 0)), name='billing_consumption_pack_nonnegative'), models.CheckConstraint(condition=models.Q(('billable_quantity__gte', 0)), name='billing_consumption_billable_nonnegative')],
            },
            bases=(billing.models.AppendOnlyMixin, models.Model),
        ),
    ]
