# Generated by Django 5.2.16 on 2026-07-19 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_printquoteconsumption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingperiod',
            name='status',
            field=models.CharField(choices=[('open', 'Otwarty'), ('closed', 'Zamknięty')], default='open', max_length=12),
        ),
        migrations.AlterField(
            model_name='planversion',
            name='billing_interval',
            field=models.CharField(choices=[('monthly', 'Miesięcznie'), ('yearly', 'Rocznie')], default='monthly', max_length=16),
        ),
        migrations.AlterField(
            model_name='planversion',
            name='tax_display',
            field=models.CharField(choices=[('inclusive', 'Podatek wliczony'), ('exclusive', 'Podatek doliczany'), ('not_applicable', 'Podatek nie dotyczy')], default='inclusive', max_length=20),
        ),
        migrations.AlterField(
            model_name='pricebookversion',
            name='tax_display',
            field=models.CharField(choices=[('inclusive', 'Podatek wliczony'), ('exclusive', 'Podatek doliczany'), ('not_applicable', 'Podatek nie dotyczy')], default='inclusive', max_length=20),
        ),
        migrations.AlterField(
            model_name='quote',
            name='status',
            field=models.CharField(choices=[('draft', 'Szkic'), ('accepted', 'Zaakceptowana'), ('expired', 'Wygasła'), ('cancelled', 'Anulowana')], default='draft', max_length=16),
        ),
        migrations.AlterField(
            model_name='quoteline',
            name='kind',
            field=models.CharField(choices=[('included', 'Limit w planie'), ('pack', 'Pakiet kart'), ('production', 'Produkcja kart'), ('shipping', 'Wysyłka'), ('tax', 'Podatek')], max_length=16),
        ),
        migrations.AlterField(
            model_name='tenantsubscription',
            name='status',
            field=models.CharField(choices=[('draft', 'Szkic'), ('active', 'Aktywna'), ('paused', 'Wstrzymana'), ('cancelled', 'Anulowana')], default='draft', max_length=16),
        ),
        migrations.AlterField(
            model_name='usageevent',
            name='kind',
            field=models.CharField(choices=[('physical_card_issued', 'Wydano kartę fizyczną'), ('virtual_card_issued', 'Wydano kartę cyfrową'), ('physical_card_produced', 'Wyprodukowano kartę fizyczną')], max_length=32),
        ),
    ]
