# Generated by Django 5.2.16 on 2026-07-19 11:18

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_alter_billingperiod_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planversion',
            name='tax_rate',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='Stawka dziesiętna, na przykład 0.2300 dla 23%.', max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.0000'))]),
        ),
    ]
