# Generated by Django 3.2.19 on 2025-04-23 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dotykacka', '0002_alter_accesstoken_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='Klient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('klient_id', models.DecimalField(decimal_places=0, max_digits=10)),
            ],
        ),
    ]
