# Generated by Django 3.2.19 on 2025-04-23 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dotykacka', '0003_klient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='klient',
            name='klient_id',
            field=models.CharField(max_length=60),
        ),
    ]
