# Generated by Django 3.2.19 on 2025-05-19 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dotykacka', '0004_alter_klient_klient_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='klient',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='klient',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='klient',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='klient',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
