# Generated by Django 5.2.1 on 2025-09-29 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dotykacka', '0005_auto_20250519_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='klient',
            name='google_jwt_url',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
