# Generated by Django 5.2.1 on 2025-09-29 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dotykacka', '0006_klient_google_jwt_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='klient',
            name='google_jwt_url',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
