# Generated by Django 5.2.1 on 2026-07-17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dotykacka", "0007_alter_klient_google_jwt_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="klient",
            name="klient_id",
            field=models.CharField(max_length=60, unique=True),
        ),
    ]
