# Generated by Django 5.2.1 on 2026-07-17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dotykacka", "0008_alter_klient_klient_id_unique"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Tenant",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=160)),
                ("legal_name", models.CharField(blank=True, max_length=200)),
                ("slug", models.SlugField(max_length=80, unique=True)),
                ("card_prefix", models.CharField(max_length=10, unique=True)),
                ("language_code", models.CharField(default="pl-pl", max_length=10)),
                ("timezone", models.CharField(default="Europe/Warsaw", max_length=64)),
                ("is_active", models.BooleanField(default=True)),
                ("public_registration_enabled", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="IntegrationConnection",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("provider", models.CharField(choices=[("dotykacka", "Dotykačka"), ("brevo", "Brevo"), ("google_wallet", "Google Wallet")], max_length=32)),
                ("enabled", models.BooleanField(default=False)),
                ("configuration", models.JSONField(blank=True, default=dict)),
                ("credentials_encrypted", models.TextField(blank=True)),
                ("last_tested_at", models.DateTimeField(blank=True, null=True)),
                ("last_success_at", models.DateTimeField(blank=True, null=True)),
                ("last_error_code", models.CharField(blank=True, max_length=80)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("tenant", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="integrations", to="dotykacka.tenant")),
            ],
        ),
        migrations.CreateModel(
            name="TenantBrand",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_name", models.CharField(max_length=160)),
                ("tagline", models.CharField(blank=True, max_length=240)),
                ("address", models.TextField(blank=True)),
                ("phone", models.CharField(blank=True, max_length=40)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("website_url", models.URLField(blank=True)),
                ("logo_path", models.CharField(blank=True, max_length=500)),
                ("background_image_path", models.CharField(blank=True, max_length=500)),
                ("email_subject", models.CharField(blank=True, max_length=240)),
                ("email_signature", models.CharField(blank=True, max_length=240)),
                ("marketing_consent_text", models.TextField(blank=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("tenant", models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name="brand", to="dotykacka.tenant")),
            ],
        ),
        migrations.CreateModel(
            name="TenantMembership",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("role", models.CharField(choices=[("owner", "Owner"), ("staff", "Staff")], default="staff", max_length=16)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("tenant", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="memberships", to="dotykacka.tenant")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="tenant_memberships", to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name="CardBatch",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=160)),
                ("card_prefix", models.CharField(max_length=10)),
                ("start_number", models.PositiveIntegerField()),
                ("end_number", models.PositiveIntegerField()),
                ("status", models.CharField(choices=[("legacy", "Legacy imported"), ("draft", "Draft"), ("generated", "Generated")], default="draft", max_length=20)),
                ("design_snapshot", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("tenant", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="card_batches", to="dotykacka.tenant")),
            ],
        ),
        migrations.AddField(
            model_name="klient",
            name="tenant",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="customers", to="dotykacka.tenant"),
        ),
        migrations.AddField(
            model_name="accesstoken",
            name="connection",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="access_tokens", to="dotykacka.integrationconnection"),
        ),
        migrations.CreateModel(
            name="PhysicalCard",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("code", models.CharField(max_length=60, unique=True)),
                ("number", models.PositiveIntegerField()),
                ("status", models.CharField(choices=[("available", "Available"), ("assigned", "Assigned"), ("printed", "Printed"), ("void", "Void")], default="available", max_length=20)),
                ("is_legacy", models.BooleanField(default=False)),
                ("front_image_path", models.CharField(blank=True, max_length=500)),
                ("back_image_path", models.CharField(blank=True, max_length=500)),
                ("barcode_image_path", models.CharField(blank=True, max_length=500)),
                ("cropped_image_path", models.CharField(blank=True, max_length=500)),
                ("apple_pass_path", models.CharField(blank=True, max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("batch", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="cards", to="dotykacka.cardbatch")),
                ("customer", models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="physical_card", to="dotykacka.klient")),
                ("tenant", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="physical_cards", to="dotykacka.tenant")),
            ],
        ),
        migrations.CreateModel(
            name="AuditEvent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("action", models.CharField(max_length=120)),
                ("object_type", models.CharField(blank=True, max_length=120)),
                ("object_id", models.CharField(blank=True, max_length=120)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("actor", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="tenant_audit_events", to=settings.AUTH_USER_MODEL)),
                ("tenant", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="audit_events", to="dotykacka.tenant")),
            ],
        ),
        migrations.AddConstraint(
            model_name="tenantmembership",
            constraint=models.UniqueConstraint(fields=("tenant", "user"), name="unique_tenant_user_membership"),
        ),
        migrations.AddConstraint(
            model_name="integrationconnection",
            constraint=models.UniqueConstraint(fields=("tenant", "provider"), name="unique_tenant_integration_provider"),
        ),
        migrations.AddConstraint(
            model_name="cardbatch",
            constraint=models.UniqueConstraint(fields=("tenant", "name"), name="unique_tenant_card_batch_name"),
        ),
        migrations.AddConstraint(
            model_name="physicalcard",
            constraint=models.UniqueConstraint(fields=("tenant", "number"), name="unique_tenant_physical_card_number"),
        ),
    ]
