# Generated by Django 5.2.1 on 2026-07-17

import django.db.models.deletion
import dotykacka.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dotykacka", "0011_require_tenant_ownership"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CardDesign",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("version", models.PositiveIntegerField()),
                ("name", models.CharField(max_length=160)),
                ("background_source", models.ImageField(blank=True, max_length=500, upload_to=dotykacka.models.card_design_background_path)),
                ("logo", models.ImageField(blank=True, max_length=500, upload_to=dotykacka.models.card_design_logo_path)),
                ("layout_preset", models.CharField(choices=[("marta_legacy", "Legacy logo and text"), ("centered", "Centered logo and text")], default="centered", max_length=32)),
                ("crop_mode", models.CharField(choices=[("center", "Center crop"), ("focal", "Focal point"), ("deterministic", "Deterministic variation")], default="deterministic", max_length=24)),
                ("focal_x", models.PositiveSmallIntegerField(default=50)),
                ("focal_y", models.PositiveSmallIntegerField(default=50)),
                ("width_px", models.PositiveIntegerField(default=1011)),
                ("height_px", models.PositiveIntegerField(default=638)),
                ("dpi", models.PositiveSmallIntegerField(default=300)),
                ("bleed_mm", models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ("logo_width_px", models.PositiveIntegerField(default=576)),
                ("front_text", models.CharField(blank=True, max_length=240)),
                ("back_text", models.TextField(blank=True)),
                ("foreground_color", models.CharField(default="#000000", max_length=7)),
                ("panel_color", models.CharField(default="#FFFFFF", max_length=7)),
                ("barcode_foreground_color", models.CharField(default="#000000", max_length=7)),
                ("barcode_background_color", models.CharField(default="#FFFFFF", max_length=7)),
                ("font_family", models.CharField(default="barlow", max_length=40)),
                ("design_checksum", models.CharField(max_length=64)),
                ("published_at", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="created_card_designs", to=settings.AUTH_USER_MODEL)),
                ("tenant", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="card_designs", to="dotykacka.tenant")),
            ],
            options={"ordering": ("-version",)},
        ),
        migrations.CreateModel(
            name="CardArtifact",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("storage_key", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("kind", models.CharField(choices=[("proof_front", "Proof front"), ("proof_back", "Proof back"), ("card_front", "Card front"), ("card_back", "Card back"), ("barcode", "Barcode"), ("manifest", "Manifest"), ("apple_pass", "Apple Wallet pass"), ("google_metadata", "Google Wallet metadata")], max_length=32)),
                ("storage_path", models.CharField(max_length=700)),
                ("sha256", models.CharField(max_length=64)),
                ("size_bytes", models.PositiveBigIntegerField()),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("batch", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="artifacts", to="dotykacka.cardbatch")),
                ("physical_card", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="artifacts", to="dotykacka.physicalcard")),
                ("tenant", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="card_artifacts", to="dotykacka.tenant")),
                ("design", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="artifacts", to="dotykacka.carddesign")),
            ],
            options={"ordering": ("-created_at",)},
        ),
        migrations.AddField(
            model_name="cardbatch",
            name="design",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="batches", to="dotykacka.carddesign"),
        ),
        migrations.CreateModel(
            name="TenantBrandRevision",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("version", models.PositiveIntegerField()),
                ("public_name", models.CharField(max_length=160)),
                ("tagline", models.CharField(blank=True, max_length=240)),
                ("address", models.TextField(blank=True)),
                ("phone", models.CharField(blank=True, max_length=40)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("website_url", models.URLField(blank=True)),
                ("email_subject", models.CharField(blank=True, max_length=240)),
                ("email_signature", models.CharField(blank=True, max_length=240)),
                ("marketing_consent_text", models.TextField(blank=True)),
                ("snapshot_checksum", models.CharField(max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="created_brand_revisions", to=settings.AUTH_USER_MODEL)),
                ("tenant", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="brand_revisions", to="dotykacka.tenant")),
            ],
            options={"ordering": ("-version",)},
        ),
        migrations.AddField(
            model_name="carddesign",
            name="brand_revision",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="card_designs", to="dotykacka.tenantbrandrevision"),
        ),
        migrations.CreateModel(
            name="WalletPass",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("apple_serial", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("google_object_id", models.CharField(blank=True, max_length=220, null=True, unique=True)),
                ("google_save_url", models.CharField(blank=True, max_length=10000)),
                ("apple_pass_path", models.CharField(blank=True, max_length=700)),
                ("apple_pass_sha256", models.CharField(blank=True, max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("customer", models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name="wallet_pass", to="dotykacka.klient")),
                ("physical_card", models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="wallet_pass", to="dotykacka.physicalcard")),
                ("tenant", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="wallet_passes", to="dotykacka.tenant")),
            ],
        ),
        migrations.AddConstraint(
            model_name="tenantbrandrevision",
            constraint=models.UniqueConstraint(fields=("tenant", "version"), name="unique_tenant_brand_revision_version"),
        ),
        migrations.AddConstraint(
            model_name="carddesign",
            constraint=models.UniqueConstraint(fields=("tenant", "version"), name="unique_tenant_card_design_version"),
        ),
        migrations.AddConstraint(
            model_name="carddesign",
            constraint=models.UniqueConstraint(fields=("tenant", "design_checksum"), name="unique_tenant_card_design_checksum"),
        ),
        migrations.AddConstraint(
            model_name="carddesign",
            constraint=models.CheckConstraint(condition=models.Q(focal_x__lte=100, focal_y__lte=100), name="card_design_focal_point_in_range"),
        ),
    ]
