# Generated by Django 5.2.16 on 2026-07-19 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dotykacka', '0014_promote_dotykacka_refresh_tokens'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardartifact',
            name='kind',
            field=models.CharField(choices=[('proof_front', 'Próbka przodu'), ('proof_back', 'Próbka tyłu'), ('card_front', 'Przód karty'), ('card_back', 'Tył karty'), ('barcode', 'Kod kreskowy'), ('manifest', 'Manifest'), ('apple_pass', 'Karta Apple Wallet'), ('google_metadata', 'Metadane Google Wallet')], max_length=32),
        ),
        migrations.AlterField(
            model_name='cardbatch',
            name='status',
            field=models.CharField(choices=[('legacy', 'Import historyczny'), ('draft', 'Szkic'), ('generated', 'Wygenerowana')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='carddesign',
            name='crop_mode',
            field=models.CharField(choices=[('center', 'Kadrowanie centralne'), ('focal', 'Punkt centralny'), ('deterministic', 'Powtarzalne zróżnicowanie')], default='deterministic', max_length=24),
        ),
        migrations.AlterField(
            model_name='carddesign',
            name='layout_preset',
            field=models.CharField(choices=[('marta_legacy', 'Historyczny układ logo i tekstu'), ('centered', 'Wyśrodkowane logo i tekst')], default='centered', max_length=32),
        ),
        migrations.AlterField(
            model_name='physicalcard',
            name='status',
            field=models.CharField(choices=[('available', 'Dostępna'), ('assigned', 'Przypisana'), ('printed', 'Wydrukowana'), ('void', 'Unieważniona')], default='available', max_length=20),
        ),
        migrations.AlterField(
            model_name='tenantmembership',
            name='role',
            field=models.CharField(choices=[('owner', 'Właściciel'), ('staff', 'Pracownik')], default='staff', max_length=16),
        ),
    ]
