# Generated by Django 5.2.17 on 2026-10-08 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dotykacka', '0015_alter_cardartifact_kind_alter_cardbatch_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integrationconnection',
            name='provider',
            field=models.CharField(choices=[('dotykacka', 'Dotykačka'), ('brevo', 'Brevo'), ('google_wallet', 'Google Wallet'), ('openai', 'OpenAI')], max_length=32),
        ),
    ]
