# Generated by Django 5.2.1 on 2026-07-18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("dotykacka", "0014_promote_dotykacka_refresh_tokens"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TenantDomain",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("hostname", models.CharField(max_length=253, unique=True)),
                ("status", models.CharField(choices=[("pending", "Pending verification"), ("verified", "Verified"), ("disabled", "Disabled")], db_index=True, default="pending", max_length=16)),
                ("is_primary", models.BooleanField(default=False)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="requested_tenant_domains", to=settings.AUTH_USER_MODEL)),
                ("tenant", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="registration_domains", to="dotykacka.tenant")),
            ],
            options={"ordering": ("tenant_id", "-is_primary", "hostname")},
        ),
        migrations.AddConstraint(
            model_name="tenantdomain",
            constraint=models.UniqueConstraint(condition=models.Q(("is_primary", True)), fields=("tenant",), name="tenant_domain_one_primary"),
        ),
    ]
