# Generated by Django 5.2.1 on 2026-07-18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0001_initial"),
        ("dotykacka", "0014_promote_dotykacka_refresh_tokens"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="tenantdomain",
            name="tenant_domain_one_primary",
        ),
        migrations.AddField(
            model_name="tenantdomain",
            name="primary_for_tenant",
            field=models.OneToOneField(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="primary_registration_domain",
                to="dotykacka.tenant",
            ),
        ),
    ]
