# Generated by Django 5.2.16 on 2026-07-19 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0004_primary_domain_marker_constraint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenantdomain',
            name='status',
            field=models.CharField(choices=[('pending', 'Oczekuje na weryfikację'), ('verified', 'Zweryfikowana'), ('disabled', 'Wyłączona')], db_index=True, default='pending', max_length=16),
        ),
    ]
