# Generated by Django 5.2.1 on 2026-07-18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MarketingLead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("full_name", models.CharField(max_length=120)),
                ("company_name", models.CharField(max_length=160)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(blank=True, max_length=40)),
                ("message", models.TextField(max_length=4000)),
                ("privacy_policy_version", models.CharField(max_length=80)),
                ("privacy_text_sha256", models.CharField(max_length=64)),
                ("content_sha256", models.CharField(max_length=64)),
                (
                    "source_path",
                    models.CharField(default="/kontakt/", max_length=300),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={"ordering": ("-created_at", "-pk")},
        )
    ]
