ServerName club.mbstudio.online
ServerTokens Prod
ServerSignature Off
TraceEnable Off
LimitRequestFieldSize 8190
LimitRequestLine 8190
LimitRequestBody 67108864

LogFormat "%a %t \"%m %U %H\" %>s %b" loyalty_safe

WSGIRestrictEmbedded On
WSGIScriptAlias / /var/www/loyalty_platform/current/loyalty_platform/wsgi.py
WSGIPythonPath /var/www/loyalty_platform/current
WSGIDaemonProcess django processes=1 threads=3 \
    python-home=/var/www/loyalty_platform/current/.venv \
    python-path=/var/www/loyalty_platform/current
WSGIProcessGroup django
WSGIApplicationGroup %{GLOBAL}

<VirtualHost *:80>
    UseCanonicalName Off
    ServerName club.mbstudio.online
    DocumentRoot /var/www/loyalty_platform/current/staticfiles

    Alias /static/ /var/www/loyalty_platform/current/staticfiles/
    <Directory /var/www/loyalty_platform/current/staticfiles/>
        Require all granted
        AllowOverride None
        Options -Indexes -ExecCGI -Includes +FollowSymLinks
        Header always set X-Content-Type-Options "nosniff"
    </Directory>

    <Directory /var/www/loyalty_platform/current/loyalty_platform/>
        <Files wsgi.py>
            Require all granted
        </Files>
    </Directory>

    ErrorLog ${APACHE_LOG_DIR}/loyalty-error.log
    CustomLog ${APACHE_LOG_DIR}/loyalty-access.log loyalty_safe
</VirtualHost>

<VirtualHost *:443>
    UseCanonicalName Off
    ServerName club.mbstudio.online
    SSLEngine on
    DocumentRoot /var/www/loyalty_platform/current/staticfiles

    Alias /static/ /var/www/loyalty_platform/current/staticfiles/
    <Directory /var/www/loyalty_platform/current/staticfiles/>
        Require all granted
        AllowOverride None
        Options -Indexes -ExecCGI -Includes +FollowSymLinks
        Header always set X-Content-Type-Options "nosniff"
    </Directory>

    <Directory /var/www/loyalty_platform/current/loyalty_platform/>
        <Files wsgi.py>
            Require all granted
        </Files>
    </Directory>

    ErrorLog ${APACHE_LOG_DIR}/loyalty-ssl-error.log
    CustomLog ${APACHE_LOG_DIR}/loyalty-ssl-access.log loyalty_safe
</VirtualHost>
