# Generated by Django 5.2.16 on 2026-07-19 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_external_identity_pending_remote_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerexternalidentity',
            name='sync_status',
            field=models.CharField(choices=[('pending', 'Oczekuje'), ('synced', 'Zsynchronizowano'), ('failed', 'Błąd'), ('disabled', 'Wyłączona')], db_index=True, default='pending', max_length=16),
        ),
    ]
