# Generated by Django 5.2.16 on 2026-09-29 11:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_alter_customerexternalidentity_sync_status'),
        ('dotykacka', '0015_alter_cardartifact_kind_alter_cardbatch_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerExportApiToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nazwa klienta lub systemu korzystającego z API.', max_length=160)),
                ('token_prefix', models.CharField(editable=False, max_length=20, unique=True)),
                ('token_hash', models.CharField(editable=False, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_customer_export_api_tokens', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_export_api_tokens', to='dotykacka.tenant')),
            ],
            options={
                'verbose_name': 'token API eksportu klientów',
                'verbose_name_plural': 'tokeny API eksportu klientów',
                'ordering': ('-created_at', '-pk'),
            },
        ),
    ]
