# Generated by Django 5.2.1 on 2026-07-17 20:21

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dotykacka', '0013_backfill_card_designs'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(db_index=True, max_length=100)),
                ('idempotency_key', models.CharField(max_length=220)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('retry', 'Retry scheduled'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], db_index=True, default='pending', max_length=16)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('max_attempts', models.PositiveSmallIntegerField(default=5)),
                ('available_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('locked_by', models.CharField(blank=True, max_length=120)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('last_error_code', models.CharField(blank=True, max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('connection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='dotykacka.integrationconnection')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='integration_jobs', to='dotykacka.tenant')),
            ],
            options={
                'ordering': ('created_at', 'pk'),
                'indexes': [models.Index(fields=['status', 'available_at', 'created_at'], name='integration_job_claim_idx')],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'idempotency_key'), name='unique_tenant_integration_job_key')],
            },
        ),
    ]
