# Generated by Django 5.2.16 on 2026-07-19 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integrationjob',
            name='status',
            field=models.CharField(choices=[('pending', 'Oczekuje'), ('running', 'W toku'), ('retry', 'Zaplanowano ponowienie'), ('succeeded', 'Zakończono'), ('failed', 'Błąd')], db_index=True, default='pending', max_length=16),
        ),
    ]
