# Generated by Django 5.2.1 on 2026-07-17 20:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dotykacka', '0013_backfill_card_designs'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DotykackaConnectState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_digest', models.CharField(max_length=64, unique=True)),
                ('session_digest', models.CharField(max_length=64)),
                ('redirect_uri', models.URLField(max_length=700)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='connector_states', to='dotykacka.integrationconnection')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dotykacka_connect_states', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dotykacka_connect_states', to='dotykacka.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='DotykackaAccessToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cloud_id', models.CharField(max_length=100)),
                ('token_encrypted', models.TextField()),
                ('obtained_at', models.DateTimeField()),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('invalidated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='encrypted_access_tokens', to='dotykacka.integrationconnection')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dotykacka_access_tokens', to='dotykacka.tenant')),
            ],
            options={
                'ordering': ('-obtained_at', '-pk'),
                'indexes': [models.Index(fields=['connection', 'cloud_id', 'expires_at'], name='dotykacka_token_lookup_idx')],
            },
        ),
    ]
