# Generated by Django 5.2.1 on 2026-07-18

import django.db.models.deletion
import enrollment.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("billing", "0002_printquoteconsumption"),
        ("customers", "0003_external_identity_pending_remote_id"),
        ("dotykacka", "0014_promote_dotykacka_refresh_tokens"),
        ("integrations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Enrollment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("registration_key", models.CharField(max_length=180)),
                ("source", models.CharField(default="public_registration", max_length=40)),
                ("brand_snapshot", models.JSONField(default=dict)),
                ("consent_snapshot", models.JSONField(default=dict)),
                ("registered_at", models.DateTimeField(auto_now_add=True)),
                ("brand_revision", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="enrollments", to="dotykacka.tenantbrandrevision")),
                ("card_design", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="enrollments", to="dotykacka.carddesign")),
                ("consent_record", models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name="enrollment", to="customers.consentrecord")),
                ("customer", models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name="enrollment", to="dotykacka.klient")),
                ("physical_card", models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name="enrollment", to="dotykacka.physicalcard")),
                ("tenant", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="enrollments", to="dotykacka.tenant")),
                ("usage_event", models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="enrollment", to="billing.usageevent")),
            ],
            options={"ordering": ("-registered_at", "-pk")},
            bases=(enrollment.models.AppendOnlyMixin, models.Model),
        ),
        migrations.CreateModel(
            name="EnrollmentAccessLink",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("purpose", models.CharField(choices=[("wallet_status", "Wallet and follow-up status")], default="wallet_status", max_length=32)),
                ("reason", models.CharField(choices=[("registration", "Registration"), ("resend", "Explicit resend")], max_length=20)),
                ("expires_at", models.DateTimeField(db_index=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="created_enrollment_access_links", to=settings.AUTH_USER_MODEL)),
                ("enrollment", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="access_links", to="enrollment.enrollment")),
            ],
            options={"ordering": ("-created_at", "-pk")},
            bases=(enrollment.models.AppendOnlyMixin, models.Model),
        ),
        migrations.CreateModel(
            name="EnrollmentEvent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("kind", models.CharField(choices=[("registered", "Registered"), ("card_assigned", "Card assigned"), ("consent_recorded", "Consent recorded"), ("issuance_recorded", "Issuance recorded"), ("followups_enqueued", "Follow-ups enqueued"), ("retry_requested", "Retry requested"), ("resend_requested", "Resend requested")], max_length=32)),
                ("idempotency_key", models.CharField(max_length=180)),
                ("reason", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("actor", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="enrollment_events", to=settings.AUTH_USER_MODEL)),
                ("enrollment", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="events", to="enrollment.enrollment")),
                ("integration_job", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="enrollment_events", to="integrations.integrationjob")),
            ],
            options={"ordering": ("created_at", "pk")},
            bases=(enrollment.models.AppendOnlyMixin, models.Model),
        ),
        migrations.CreateModel(
            name="EnrollmentFollowUp",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("kind", models.CharField(max_length=100)),
                ("generation", models.PositiveIntegerField(default=1)),
                ("operation", models.CharField(choices=[("initial", "Initial enrollment"), ("resend", "Explicit resend")], max_length=16)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("enrollment", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="followups", to="enrollment.enrollment")),
                ("integration_job", models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name="enrollment_followup", to="integrations.integrationjob")),
                ("requested_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="requested_enrollment_followups", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ("created_at", "pk")},
            bases=(enrollment.models.AppendOnlyMixin, models.Model),
        ),
        migrations.AddConstraint(
            model_name="enrollment",
            constraint=models.UniqueConstraint(fields=("tenant", "registration_key"), name="enrollment_unique_tenant_registration_key"),
        ),
        migrations.AddConstraint(
            model_name="enrollmentevent",
            constraint=models.UniqueConstraint(fields=("enrollment", "idempotency_key"), name="enrollment_unique_event_key"),
        ),
        migrations.AddConstraint(
            model_name="enrollmentfollowup",
            constraint=models.UniqueConstraint(fields=("enrollment", "kind", "generation"), name="enrollment_unique_followup_generation"),
        ),
        migrations.AddConstraint(
            model_name="enrollmentfollowup",
            constraint=models.CheckConstraint(condition=models.Q(("generation__gt", 0)), name="enrollment_followup_generation_positive"),
        ),
    ]
