# Generated by Django 5.2.16 on 2026-07-19 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollmentaccesslink',
            name='purpose',
            field=models.CharField(choices=[('wallet_status', 'Status Wallet i zadań dodatkowych')], default='wallet_status', max_length=32),
        ),
        migrations.AlterField(
            model_name='enrollmentaccesslink',
            name='reason',
            field=models.CharField(choices=[('registration', 'Rejestracja'), ('resend', 'Jawne ponowne wysłanie')], max_length=20),
        ),
        migrations.AlterField(
            model_name='enrollmentevent',
            name='kind',
            field=models.CharField(choices=[('registered', 'Zarejestrowano'), ('card_assigned', 'Przypisano kartę'), ('consent_recorded', 'Zapisano zgodę'), ('issuance_recorded', 'Zapisano wydanie'), ('followups_enqueued', 'Dodano zadania dodatkowe'), ('retry_requested', 'Zlecono ponowienie'), ('resend_requested', 'Zlecono ponowne wysłanie')], max_length=32),
        ),
        migrations.AlterField(
            model_name='enrollmentfollowup',
            name='operation',
            field=models.CharField(choices=[('initial', 'Pierwsza rejestracja'), ('resend', 'Jawne ponowne wysłanie')], max_length=16),
        ),
    ]
