# Generated by Django 5.2.1 on 2026-07-18

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("dotykacka", "0014_promote_dotykacka_refresh_tokens"),
    ]

    operations = [
        migrations.CreateModel(
            name="RateLimitBucket",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("scope", models.CharField(max_length=80)),
                ("identity_hash", models.CharField(max_length=64)),
                ("window_started_at", models.DateTimeField()),
                ("request_count", models.PositiveIntegerField(default=0)),
                ("limited_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="WorkerHeartbeat",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("worker_type", models.CharField(choices=[("integration", "Integration worker"), ("printing", "Print worker"), ("monitor", "Operations monitor")], max_length=24)),
                ("worker_id", models.CharField(max_length=160)),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("last_seen_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ("processed_count", models.PositiveBigIntegerField(default=0)),
                ("status", models.CharField(default="running", max_length=32)),
                ("safe_metadata", models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name="OperationalAlert",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("fingerprint", models.CharField(max_length=191, unique=True)),
                ("category", models.CharField(db_index=True, max_length=48)),
                ("severity", models.CharField(choices=[("warning", "Warning"), ("critical", "Critical")], max_length=16)),
                ("status", models.CharField(choices=[("open", "Open"), ("acknowledged", "Acknowledged"), ("resolved", "Resolved")], db_index=True, default="open", max_length=16)),
                ("title", models.CharField(max_length=180)),
                ("safe_summary", models.TextField(max_length=1000)),
                ("source_type", models.CharField(blank=True, max_length=80)),
                ("source_id", models.CharField(blank=True, max_length=120)),
                ("occurrences", models.PositiveIntegerField(default=1)),
                ("first_seen_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("last_seen_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("acknowledged_at", models.DateTimeField(blank=True, null=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("acknowledged_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="acknowledged_operational_alerts", to=settings.AUTH_USER_MODEL)),
                ("resolved_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="resolved_operational_alerts", to=settings.AUTH_USER_MODEL)),
                ("tenant", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="operational_alerts", to="dotykacka.tenant")),
            ],
            options={"ordering": ("status", "-severity", "-last_seen_at", "-pk")},
        ),
        migrations.CreateModel(
            name="OperationalAlertEvent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("kind", models.CharField(choices=[("detected", "Detected"), ("seen", "Seen again"), ("acknowledged", "Acknowledged"), ("resolved", "Resolved"), ("reopened", "Reopened")], max_length=24)),
                ("reason", models.TextField(blank=True, max_length=1000)),
                ("safe_snapshot", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("actor", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="operational_alert_events", to=settings.AUTH_USER_MODEL)),
                ("alert", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="events", to="operations.operationalalert")),
            ],
            options={"ordering": ("created_at", "pk")},
        ),
        migrations.AddConstraint(
            model_name="ratelimitbucket",
            constraint=models.UniqueConstraint(fields=("scope", "identity_hash", "window_started_at"), name="operations_unique_rate_limit_window"),
        ),
        migrations.AddIndex(
            model_name="ratelimitbucket",
            index=models.Index(fields=["scope", "window_started_at"], name="operations_rate_window_idx"),
        ),
        migrations.AddConstraint(
            model_name="workerheartbeat",
            constraint=models.UniqueConstraint(fields=("worker_type", "worker_id"), name="operations_unique_worker_heartbeat"),
        ),
        migrations.AddIndex(
            model_name="workerheartbeat",
            index=models.Index(fields=["worker_type", "last_seen_at"], name="operations_worker_seen_idx"),
        ),
    ]
