# Generated by Django 5.2.16 on 2026-07-19 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operationalalert',
            name='severity',
            field=models.CharField(choices=[('warning', 'Ostrzeżenie'), ('critical', 'Krytyczny')], max_length=16),
        ),
        migrations.AlterField(
            model_name='operationalalert',
            name='status',
            field=models.CharField(choices=[('open', 'Otwarty'), ('acknowledged', 'Potwierdzony'), ('resolved', 'Rozwiązany')], db_index=True, default='open', max_length=16),
        ),
        migrations.AlterField(
            model_name='operationalalertevent',
            name='kind',
            field=models.CharField(choices=[('detected', 'Wykryto'), ('seen', 'Wykryto ponownie'), ('acknowledged', 'Potwierdzono'), ('resolved', 'Rozwiązano'), ('reopened', 'Otwarto ponownie')], max_length=24),
        ),
        migrations.AlterField(
            model_name='workerheartbeat',
            name='worker_type',
            field=models.CharField(choices=[('integration', 'Proces integracji'), ('printing', 'Proces druku'), ('monitor', 'Monitor operacyjny')], max_length=24),
        ),
    ]
