# Generated by Django 5.2.1 on 2026-07-17 23:27

import django.db.models.deletion
import django.utils.timezone
import printing.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0002_printquoteconsumption'),
        ('card_artwork', '0001_crop_plan'),
        ('dotykacka', '0014_promote_dotykacka_refresh_tokens'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PrintRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('allocated', 'Allocated'), ('generating', 'Generating'), ('ready', 'Ready'), ('failed', 'Failed'), ('printing', 'Printing'), ('printed', 'Printed'), ('packed', 'Packed'), ('dispatched', 'Dispatched'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], db_index=True, default='submitted', max_length=20)),
                ('idempotency_key', models.CharField(max_length=180)),
                ('quantity', models.PositiveIntegerField()),
                ('proof_checksum', models.CharField(max_length=64)),
                ('delivery_name', models.CharField(max_length=160)),
                ('delivery_address_line1', models.CharField(max_length=240)),
                ('delivery_address_line2', models.CharField(blank=True, max_length=240)),
                ('delivery_postal_code', models.CharField(max_length=24)),
                ('delivery_city', models.CharField(max_length=120)),
                ('delivery_country', models.CharField(default='PL', max_length=2)),
                ('notes', models.TextField(blank=True)),
                ('snapshot', models.JSONField(default=dict)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('design', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='print_requests', to='dotykacka.carddesign')),
                ('proof_back', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='print_requests_as_back_proof', to='dotykacka.cardartifact')),
                ('proof_front', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='print_requests_as_front_proof', to='dotykacka.cardartifact')),
                ('quote', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='print_request', to='billing.quote')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submitted_print_requests', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='print_requests', to='dotykacka.tenant')),
            ],
            options={
                'ordering': ('-submitted_at', '-pk'),
            },
        ),
        migrations.CreateModel(
            name='PrintRequestEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, max_length=20)),
                ('to_status', models.CharField(choices=[('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('allocated', 'Allocated'), ('generating', 'Generating'), ('ready', 'Ready'), ('failed', 'Failed'), ('printing', 'Printing'), ('printed', 'Printed'), ('packed', 'Packed'), ('dispatched', 'Dispatched'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], max_length=20)),
                ('reason', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='print_request_events', to=settings.AUTH_USER_MODEL)),
                ('print_request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='status_events', to='printing.printrequest')),
            ],
            options={
                'ordering': ('created_at', 'pk'),
            },
            bases=(printing.models.AppendOnlyMixin, models.Model),
        ),
        migrations.CreateModel(
            name='PrintRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('allocated', 'Allocated'), ('generating', 'Generating'), ('ready', 'Ready'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='allocated', max_length=16)),
                ('quantity', models.PositiveIntegerField()),
                ('start_number', models.PositiveIntegerField()),
                ('end_number', models.PositiveIntegerField()),
                ('layout_snapshot', models.JSONField(default=dict)),
                ('design_snapshot', models.JSONField(default=dict)),
                ('quote_snapshot', models.JSONField(default=dict)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='print_run', to='dotykacka.cardbatch')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_print_runs', to=settings.AUTH_USER_MODEL)),
                ('design', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='print_runs', to='dotykacka.carddesign')),
                ('print_request', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='print_run', to='printing.printrequest')),
                ('quote', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='print_run', to='billing.quote')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='print_runs', to='dotykacka.tenant')),
            ],
            options={
                'ordering': ('-created_at', '-pk'),
            },
        ),
        migrations.CreateModel(
            name='PrintPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storage_key', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('storage_path', models.CharField(max_length=700)),
                ('sha256', models.CharField(max_length=64)),
                ('size_bytes', models.PositiveBigIntegerField()),
                ('manifest', models.JSONField(default=dict)),
                ('validated_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('print_run', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='package', to='printing.printrun')),
            ],
            bases=(printing.models.AppendOnlyMixin, models.Model),
        ),
        migrations.CreateModel(
            name='PrintJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idempotency_key', models.CharField(max_length=180, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('retry', 'Retry scheduled'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=16)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('max_attempts', models.PositiveSmallIntegerField(default=3)),
                ('available_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('locked_by', models.CharField(blank=True, max_length=120)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('last_error_code', models.CharField(blank=True, max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('print_run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='printing.printrun')),
            ],
            options={
                'ordering': ('created_at', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='FulfillmentEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('printing', 'Printing started'), ('printed', 'Printed'), ('packed', 'Packed'), ('dispatched', 'Dispatched'), ('delivered', 'Delivered'), ('correction', 'Correction')], db_index=True, max_length=16)),
                ('idempotency_key', models.CharField(max_length=220)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('reference', models.CharField(blank=True, max_length=160)),
                ('notes', models.TextField(blank=True)),
                ('reason', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fulfillment_events', to=settings.AUTH_USER_MODEL)),
                ('compensates', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='correction_event', to='printing.fulfillmentevent')),
                ('physical_card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fulfillment_events', to='dotykacka.physicalcard')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fulfillment_events', to='dotykacka.tenant')),
                ('print_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fulfillment_events', to='printing.printrequest')),
                ('print_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fulfillment_events', to='printing.printrun')),
            ],
            options={
                'ordering': ('occurred_at', 'pk'),
            },
            bases=(printing.models.AppendOnlyMixin, models.Model),
        ),
        migrations.CreateModel(
            name='PrintRunCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('code_snapshot', models.CharField(max_length=60)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('back_artifact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='print_run_cards_as_back', to='dotykacka.cardartifact')),
                ('barcode_artifact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='print_run_cards_as_barcode', to='dotykacka.cardartifact')),
                ('crop_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='print_run_cards', to='card_artwork.cropplan')),
                ('front_artifact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='print_run_cards_as_front', to='dotykacka.cardartifact')),
                ('physical_card', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='production_allocation', to='dotykacka.physicalcard')),
                ('print_run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='run_cards', to='printing.printrun')),
            ],
            options={
                'ordering': ('position',),
            },
        ),
        migrations.AddConstraint(
            model_name='printrequest',
            constraint=models.UniqueConstraint(fields=('tenant', 'idempotency_key'), name='printing_unique_tenant_request_key'),
        ),
        migrations.AddConstraint(
            model_name='printrequest',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='printing_request_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='printrun',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='printing_run_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='printrun',
            constraint=models.CheckConstraint(condition=models.Q(('end_number__gte', models.F('start_number'))), name='printing_run_number_range_valid'),
        ),
        migrations.AddIndex(
            model_name='printjob',
            index=models.Index(fields=['status', 'available_at', 'created_at'], name='printing_job_claim_idx'),
        ),
        migrations.AddConstraint(
            model_name='fulfillmentevent',
            constraint=models.UniqueConstraint(fields=('tenant', 'idempotency_key'), name='printing_unique_tenant_fulfillment_key'),
        ),
        migrations.AddConstraint(
            model_name='printruncard',
            constraint=models.UniqueConstraint(fields=('print_run', 'position'), name='printing_unique_run_card_position'),
        ),
        migrations.AddConstraint(
            model_name='printruncard',
            constraint=models.CheckConstraint(condition=models.Q(('position__gt', 0)), name='printing_run_card_position_positive'),
        ),
    ]
