# Generated by Django 5.2.16 on 2026-07-19 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fulfillmentevent',
            name='event_type',
            field=models.CharField(choices=[('printing', 'Rozpoczęto druk'), ('printed', 'Wydrukowano'), ('packed', 'Spakowano'), ('dispatched', 'Wysłano'), ('delivered', 'Dostarczono'), ('correction', 'Korekta')], db_index=True, max_length=16),
        ),
        migrations.AlterField(
            model_name='printjob',
            name='status',
            field=models.CharField(choices=[('pending', 'Oczekuje'), ('running', 'W toku'), ('retry', 'Zaplanowano ponowienie'), ('succeeded', 'Zakończono'), ('failed', 'Błąd'), ('cancelled', 'Anulowano')], db_index=True, default='pending', max_length=16),
        ),
        migrations.AlterField(
            model_name='printrequest',
            name='status',
            field=models.CharField(choices=[('submitted', 'Złożone'), ('approved', 'Zatwierdzone'), ('rejected', 'Odrzucone'), ('allocated', 'Przydzielono karty'), ('generating', 'Generowanie'), ('ready', 'Gotowe'), ('failed', 'Błąd'), ('printing', 'W druku'), ('printed', 'Wydrukowane'), ('packed', 'Spakowane'), ('dispatched', 'Wysłane'), ('delivered', 'Dostarczone'), ('cancelled', 'Anulowane')], db_index=True, default='submitted', max_length=20),
        ),
        migrations.AlterField(
            model_name='printrequestevent',
            name='to_status',
            field=models.CharField(choices=[('submitted', 'Złożone'), ('approved', 'Zatwierdzone'), ('rejected', 'Odrzucone'), ('allocated', 'Przydzielono karty'), ('generating', 'Generowanie'), ('ready', 'Gotowe'), ('failed', 'Błąd'), ('printing', 'W druku'), ('printed', 'Wydrukowane'), ('packed', 'Spakowane'), ('dispatched', 'Wysłane'), ('delivered', 'Dostarczone'), ('cancelled', 'Anulowane')], max_length=20),
        ),
        migrations.AlterField(
            model_name='printrun',
            name='status',
            field=models.CharField(choices=[('allocated', 'Przydzielono karty'), ('generating', 'Generowanie'), ('ready', 'Gotowy'), ('failed', 'Błąd'), ('cancelled', 'Anulowany')], db_index=True, default='allocated', max_length=16),
        ),
    ]
